vich_uploader:
    db_driver: orm

    mappings:
        logo:
            uri_prefix: /images/members
            upload_destination: '%kernel.project_dir%/public/images/members'
            namer: vich_uploader.namer_uniqid
        image:
            uri_prefix: /images/members
            upload_destination: '%kernel.project_dir%/public/images/members'
            namer: vich_uploader.namer_uniqid